server:
  port: 9999
#  servlet:
#    context-path: /workflow

spring:
  application:
    name: sli-workflow
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化
      initial-size: 5
      # 最大的连接书
      max-active: 20
      # 最小连接数
      min-idle: 5
      # 最大等待时间
      max-wait: 60000
      # 申请连接时时候检测
      test-while-idle: true
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      max-evictable-idle-time-millis: 60000
      # 毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接
      min-evictable-idle-time-millis: 20000
      # 检测是否是有效sql mysql 是 x oracle 是 select 1 from dual
#      validation-query: select 'x'
#      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
#      test-on-borrow: true
#      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
#      test-on-return: true
#      # 当数据库抛出不可恢复的异常时,抛弃该连接
#      # exception-sorter: true
#      # 置访问druid监控页的账号和密码,默认没有
#      stat-view-servlet:
#        login-username: admin
#        login-password: admin
#
#      # 过滤器
#      filters: stat,wall
#      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#      # 开启web filter
#      web-stat-filter:
#        enabled: true
  redis:
    host: 127.0.0.1
    port: 6379
    #    password: eastcomsfnscp
    timeout: 5000ms
    database: 1  # 指定存储的数据是哪个库
    jedis:
#    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 100
        min-idle: 1
#  security:
#    user:
#      name:
#        sli
#      password: 97

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    instance-id: sli_eureka:${spring.application.name}:${server.port}