server:
  port: 9999
  servlet:
    context-path: /workflow

spring:
  application:
    name: sli-workflow

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka/
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#    instance-id: sli_eureka:${spring.application.name}:${server.port}