server:
  port: 4000
#  servlet:
#    context-path: /gateway

spring:
  application:
    name: sli-gateway
#  cloud:
#    config:
#      uri: http://localhost:8888
#      password: ${CONFIG_SERVICE_PASSWORD:password}
#      username: user
#      name: gateway
#      profile: ${spring.profiles.active:dev}
#      fail-fast: true #是否启动快速失败功能，功能开启则优先判断config server是否正常
#          retry:
#            initial-interval: 1000 #最初重试间隔为 1000 毫秒
#            max-attempts: 6 #最多重试 6 次
#            max-interval: 2000 #最长重试间隔为 2000 毫秒
#            multiplier: 1.1 #每次重试失败后，重试间隔所增加的倍数
#      label: ${spring.profiles.active:master}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: sli_eureka:${spring.application.name}:${server.port}

ribbon:
  ReadTimeout: 50000
  ConnectTimeout: 50000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false
  eager-load:
    enabled: true
    clients: sli-auth,sli-registry, sli-config,sli-workflow

zuul:
  retryable: true
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  AuthHeaderFilter:   #配置过滤器是否打开
    pre:
      disable: false
  routes:
    auth-route:
      path: /uaa/**
      serviceId: sli-auth
      stripPrefix: false
      sensitiveHeaders:

    registry-route:
      path: /registry/**
      serviceId: sli-registry
      stripPrefix: false
      sensitiveHeaders:

    config-route:
      path: /config/**
      serviceId: sli-config
      stripPrefix: false
      sensitiveHeaders:

    workflow-route:
      path: /workflow/**
      serviceId: sli-workflow
      stripPrefix: false
      sensitiveHeaders:

  add-proxy-headers: true
  add-host-header: true