server:
  port: 4000
#  servlet:
#    context-path: /gateway

spring:
  application:
    name: demo-gateway
  cloud:
    config:
      uri: http://localhost:8888
      password: ${CONFIG_SERVICE_PASSWORD:password}
      username: user
      name: gateway
      profile: ${spring.profiles.active:dev}
      fail-fast: true #是否启动快速失败功能，功能开启则优先判断config server是否正常
#          retry:
#            initial-interval: 1000 #最初重试间隔为 1000 毫秒
#            max-attempts: 6 #最多重试 6 次
#            max-interval: 2000 #最长重试间隔为 2000 毫秒
#            multiplier: 1.1 #每次重试失败后，重试间隔所增加的倍数
#      label: ${spring.profiles.active:master}


zuul:
  retryable: true
  ribbon:
    eager-load:
      enabled: true
      clients: demo-auth,demo-registry, demo-config,demo-workflow
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
  forceOriginalQueryStringEncoding: true
  AuthHeaderFilter:   #配置过滤器是否打开
    pre:
      disable: false
  routes:
    auth-route:
      path: /uaa/**
      serviceId: demo-auth
      stripPrefix: false
      sensitiveHeaders:

    registry-route:
      path: /registry/**
      serviceId: demo-registry
      stripPrefix: false
      sensitiveHeaders:

    config-route:
      path: /config/**
      serviceId: demo-config
      stripPrefix: false
      sensitiveHeaders:

    workflow-route:
      path: /workflow/**
      serviceId: demo-workflow
      stripPrefix: false
      sensitiveHeaders:

  add-proxy-headers: true
  add-host-header: true