# Spring
spring:
  redis:
    host: localhost
    port: 6379
#    password:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ry-config?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  main:
#    # 开启重名Bean覆盖
#    allow-bean-definition-overriding: true

# Mybatis配置
mybatis:
#   搜索指定包别名
  typeAliasesPackage: com.sli
#   配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/*.xml

#请求处理的超时时间
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

# feign 配置
feign:
  sentinel:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000
  compression:
    request:
      enabled: true
    response:
      enabled: true

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'

# 认证配置
security:
  oauth2:
    client:
      client-id: ruoyi
      client-secret: 123456
      scope: server
    resource:
      loadBalanced: true
      token-info-uri: http://sli-auth/oauth/check_token
    ignore:
      urls:
      - /v2/api-docs
      - /actuator/**
      - /user/info/*
      - /operlog
      - /logininfor
