spring:
  application:
    name: demo-registry
  cloud:
    config:
      uri: http://localhost:8888
      password: ${CONFIG_SERVICE_PASSWORD:password}
      username: user
      name: registry
      profile: ${spring.profiles.active:dev}
      fail-fast: true #是否启动快速失败功能，功能开启则优先判断config server是否正常
#          retry:
#            initial-interval: 1000 #最初重试间隔为 1000 毫秒
#            max-attempts: 6 #最多重试 6 次
#            max-interval: 2000 #最长重试间隔为 2000 毫秒
#            multiplier: 1.1 #每次重试失败后，重试间隔所增加的倍数
#      label: ${spring.profiles.active:master}