server:
  port: 8087
  servlet:
    context-path: /config

spring:
  application:
    name: demo-config

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/registry/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: sli:${spring.application.name}:${spring.application.instance_id}:${server.port}}